# Generated by Django 5.2.6 on 2025-09-24 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutions', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Institutions.institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('principal', 'principal'), ('deputy_principal', 'deputy_principal'), ('admin', 'admin'), ('super_admin', 'super_admin')], default='teacher', max_length=50),
        ),
    ]
