# Generated by Django 5.2.6 on 2025-09-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutions', '0002_institution_status'),
        ('Users', '0002_alter_user_institution_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Institutions.institution'),
        ),
    ]
