# Generated by Django 5.2.6 on 2025-09-30 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionClasses', '0002_remove_institutionclass_created_by'),
        ('Users', '0005_user_user_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_class', to='InstitutionClasses.institutionclass'),
        ),
    ]
