# Generated by Django 5.2.6 on 2025-10-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_user_user_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="adm_no",
            field=models.IntegerField(default=0, verbose_name="admission_number"),
        ),
    ]
