# Generated by Django 5.2.6 on 2025-09-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institutions', '0003_alter_institution_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50, unique=True)),
                ('exam_term', models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], default='One', max_length=10)),
                ('exam_year', models.IntegerField(default=2025)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('exam_status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('deleted', 'deleted'), ('released', 'released'), ('paused', 'paused')], default='active', max_length=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='Institutions.institution')),
            ],
        ),
    ]
