# Generated by Django 5.2.6 on 2025-09-30 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionClasses', '0002_remove_institutionclass_created_by'),
        ('Subjects', '0003_alter_subject_subject_code'),
        ('Teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='InstitutionClasses.institutionclass'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='Subjects.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
