# Generated by Django 5.2.6 on 2025-09-29 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institutions', '0003_alter_institution_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=20)),
                ('institution_status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('deleted', 'deleted'), ('graduated', 'graduated')], default='active', max_length=40)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Institutions.institution')),
            ],
        ),
    ]
