# Generated by Django 5.2.6 on 2025-09-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstitutionClasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionclass',
            name='created_by',
        ),
    ]
