# Generated by Django 5.2.6 on 2025-10-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InstitutionClasses", "0002_remove_institutionclass_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institutionclass",
            old_name="institution_status",
            new_name="class_status",
        ),
    ]
