# Generated by Django 5.2.6 on 2025-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
