# Generated by Django 5.2.6 on 2025-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0002_subject_status_subject_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.IntegerField(),
        ),
    ]
