# Generated by Django 5.2.6 on 2025-09-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('national', 'national'), ('extra_county', 'extra_county'), ('county', 'county')], max_length=20)),
                ('institutionType', models.CharField(choices=[('day', 'day'), ('boarding', 'boarding')], max_length=10)),
                ('studentGender', models.CharField(choices=[('boys', 'boys'), ('girls', 'girls'), ('mixed', 'mixed')], max_length=10)),
                ('is_sne', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
            ],
        ),
    ]
