# Generated by Django 5.2.6 on 2025-09-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('deleted', 'deleted')], default='active', max_length=20),
        ),
    ]
