# Generated by Django 5.2.6 on 2025-10-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Institutions", "0003_alter_institution_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="category",
            field=models.CharField(
                choices=[
                    ("national", "national"),
                    ("extra_county", "extra_county"),
                    ("county", "county"),
                    ("None", "None"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institutionType",
            field=models.CharField(
                choices=[("day", "day"), ("boarding", "boarding"), ("None", "None")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="studentGender",
            field=models.CharField(
                choices=[
                    ("boys", "boys"),
                    ("girls", "girls"),
                    ("mixed", "mixed"),
                    ("None", "None"),
                ],
                max_length=10,
            ),
        ),
    ]
